[package]
name = "ofslinux-server-launcher"
version = "0.1.0"
authors = ["Sir Matrix <killer20816@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.33"
clap = "2.33.3"
rusqlite = "0.24.0"
